version: 2.1

workflows:
  test-and-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+(-alpha\d+)?$/
      - deploy:
          requires:
            - test
          context: JFrog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+(-alpha\d+)?$/
jobs:
  test:
    docker:
      - image: clojure:lein-2.8.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-jars-{{ checksum "project.clj" }}
      - run:
          name: Run the tests
          command: |
            lein test :unit
      - save_cache:
          key: v1-jars-{{ checksum "project.clj" }}
          paths:
            - /root/.m2
  deploy:
    docker:
      - image: clojure:lein-2.8.1
    steps:
      - checkout
      - run:
          name: import GPG key
          command: echo -e "$GPG_KEY_V2" | gpg --import
      - run:
          name: Deploy JAR
          command: lein deploy clojars
